/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    team: Team;
    'team-groups': TeamGroup;
    projects: Project;
    events: Event;
    faq: Faq;
    sponsors: Sponsor;
    'sponsor-tiers': SponsorTier;
    companies: Company;
    media: Media;
    'blog-posts': BlogPost;
    'waitlist-signups': WaitlistSignup;
    'analytics-events': AnalyticsEvent;
    'consent-records': ConsentRecord;
    'applicant-files': ApplicantFile;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    'team-groups': TeamGroupsSelect<false> | TeamGroupsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    'sponsor-tiers': SponsorTiersSelect<false> | SponsorTiersSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'waitlist-signups': WaitlistSignupsSelect<false> | WaitlistSignupsSelect<true>;
    'analytics-events': AnalyticsEventsSelect<false> | AnalyticsEventsSelect<true>;
    'consent-records': ConsentRecordsSelect<false> | ConsentRecordsSelect<true>;
    'applicant-files': ApplicantFilesSelect<false> | ApplicantFilesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'de') | ('en' | 'de')[];
  globals: {
    'site-config': SiteConfig;
    membership: Membership;
    legal: Legal;
    partner: Partner;
    about: About;
    homepage: Homepage;
    'tech-tour': TechTour;
  };
  globalsSelect: {
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
    membership: MembershipSelect<false> | MembershipSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
    partner: PartnerSelect<false> | PartnerSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'tech-tour': TechTourSelect<false> | TechTourSelect<true>;
  };
  locale: 'en' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  _order?: string | null;
  name: string;
  role: string;
  /**
   * Assign this person to one or more teams, with the role they hold in each. Leave a role blank to reuse the main role above.
   */
  teamMemberships?:
    | {
        team: number | TeamGroup;
        /**
         * Optional — role in this team; falls back to the main role above.
         */
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  category: 'member' | 'adviser';
  image?: (number | null) | Media;
  bio: string;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  companies?: (number | Company)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Team sections for the Team page (e.g. Engineering, Design). Assign people to a team under each person in "Team".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-groups".
 */
export interface TeamGroup {
  id: number;
  name: string;
  /**
   * Optional logo/image shown beside the team heading.
   */
  logo?: (number | null) | Media;
  /**
   * Lower shows first (e.g. 10, 20, 30 …).
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Companies our team members have worked at — shown as a logo wall on the Team page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  ngoPartner: string;
  /**
   * Lowercase, hyphenated (e.g. "lebenshilfe-muenchen"). Needed for the detail page.
   */
  slug?: string | null;
  featured?: boolean | null;
  description: string;
  image?: (number | null) | Media;
  technologies?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  status: 'active' | 'completed' | 'recruiting';
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Who works on this project. Shown on the Team page under each person — no case study needed. The case study's "Team" block reuses this list.
   */
  team?:
    | {
        member: number | Team;
        /**
         * Role on this project (e.g. "Project Lead"). Falls back to the member's main role if blank.
         */
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The case-study page headline (falls back to the project title).
   */
  impactHeadline?: string | null;
  /**
   * A one-line impact highlight shown under the headline (e.g. "Saves ~150 companions hours of paperwork a month").
   */
  impact?: string | null;
  /**
   * The body of the case-study page. Add, remove and reorder blocks freely — text sections, quote, gallery, product demo, timeline, team and FAQ.
   */
  layout?:
    | (
        | {
            /**
             * Optional section heading (e.g. "The challenge").
             */
            heading?: string | null;
            /**
             * Paragraph text. Separate paragraphs with a blank line.
             */
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            text: string;
            author?: string | null;
            role?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            /**
             * Optional section heading (e.g. "From the workshop").
             */
            heading?: string | null;
            /**
             * Use "Product shots" for app screens and device mock-ups, "Photographs" for workshops, on-site visits and presentations.
             */
            layout?: ('stage' | 'photos') | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            /**
             * Optional section heading (e.g. "See it in action").
             */
            heading?: string | null;
            /**
             * A screen recording (MP4), served from our own domain. Keep it short and silent-friendly — it plays on tap, never on its own.
             */
            video: number | Media;
            /**
             * Still frame shown before playback. Recommended for embeds.
             */
            poster?: (number | null) | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'demo';
          }
        | {
            /**
             * Optional section heading (e.g. "How it came together").
             */
            heading?: string | null;
            points?:
              | {
                  /**
                   * Shown inside the circle — a number (1, 2, 3) or a symbol (e.g. ✓). Leave blank to auto-number by position.
                   */
                  marker?: string | null;
                  /**
                   * Small badge above the title (e.g. "March 2026" or "Week 2").
                   */
                  timing?: string | null;
                  title: string;
                  subtitle?: string | null;
                  /**
                   * Progress marker: set "Current" on the phase the project is in — earlier steps then show as done, later ones as upcoming. Leave every point blank for a plain timeline.
                   */
                  state?: ('done' | 'current' | 'upcoming') | null;
                  /**
                   * Optional screenshot or mock-up shown with this step.
                   */
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            /**
             * Optional section heading (e.g. "The team behind it").
             */
            heading?: string | null;
            /**
             * Leave empty to show the project's Team (set further up this page). Add rows only to show a different list here.
             */
            members?:
              | {
                  member: number | Team;
                  /**
                   * Role on this project (e.g. "Project Lead"). Falls back to the member's main role if blank.
                   */
                  role?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  date: string;
  time: string;
  location: string;
  description: string;
  type: 'Hackathon' | 'Workshop' | 'Info-session' | 'Social';
  isUpcoming?: boolean | null;
  link?: {
    label?: string | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: ('general' | 'membership' | 'projects' | 'technical') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  url?: string | null;
  /**
   * Which tier section this sponsor appears in (managed in Sponsor Tiers).
   */
  tierRef?: (number | null) | SponsorTier;
  /**
   * Deprecated — use the Tier relationship above.
   */
  tier?: ('platinum' | 'gold' | 'silver' | 'bronze' | 'partner') | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tier sections for the Sponsors page (e.g. Platinum, Gold …).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsor-tiers".
 */
export interface SponsorTier {
  id: number;
  label: string;
  /**
   * Lower shows first (e.g. Platinum 10, Gold 20, Silver 30 …).
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  publishedAt: string;
  excerpt: string;
  featuredImage?: (number | null) | Media;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  author?: (number | null) | Team;
  project?: (number | null) | Project;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * People who asked to be notified when membership applications reopen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-signups".
 */
export interface WaitlistSignup {
  id: number;
  email: string;
  /**
   * Site language the person signed up in.
   */
  locale?: string | null;
  /**
   * Where this submission came from — captured from the landing URL (?src / utm_*) and carried through the session. Empty for direct/organic visits. Used only in aggregate for campaign analysis.
   */
  attribution?: {
    /**
     * Campaign tag from ?src=, or utm_source (e.g. "poster-tumsom").
     */
    source?: string | null;
    /**
     * Normalised traffic channel, derived from the tag + referrer: campaign (tagged link), organic_search, social, referral, or direct.
     */
    channel?: ('campaign' | 'organic_search' | 'social' | 'referral' | 'direct') | null;
    /**
     * utm_medium (e.g. poster, qr, social, newsletter).
     */
    medium?: string | null;
    /**
     * utm_campaign.
     */
    campaign?: string | null;
    /**
     * utm_content — distinguishes creatives/variants.
     */
    content?: string | null;
    /**
     * Referring site host (e.g. instagram.com), when the browser sends one.
     */
    referrer?: string | null;
    /**
     * First path the visitor landed on this session.
     */
    landingPath?: string | null;
    /**
     * Random per-visit id (sessionStorage). Links this conversion to the behavioural funnel; not a stable identifier, not personal data.
     */
    sessionId?: string | null;
    /**
     * When attribution was first captured this session.
     */
    firstSeenAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Cookieless behavioural events (page views, form starts, conversions) for campaign & funnel analysis. No cookies, no IP, no personal data — a random per-visit session id links events to a conversion.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events".
 */
export interface AnalyticsEvent {
  id: number;
  type:
    | 'landing'
    | 'pageview'
    | 'cta_click'
    | 'form_start'
    | 'conversion'
    | 'outbound_click'
    | 'booking_started'
    | 'booking_completed';
  /**
   * Page path where the event occurred.
   */
  path?: string | null;
  /**
   * Event detail — CTA id, form name, conversion kind, or link host.
   */
  label?: string | null;
  /**
   * Site language at the time.
   */
  locale?: string | null;
  /**
   * Where this submission came from — captured from the landing URL (?src / utm_*) and carried through the session. Empty for direct/organic visits. Used only in aggregate for campaign analysis.
   */
  attribution?: {
    /**
     * Campaign tag from ?src=, or utm_source (e.g. "poster-tumsom").
     */
    source?: string | null;
    /**
     * Normalised traffic channel, derived from the tag + referrer: campaign (tagged link), organic_search, social, referral, or direct.
     */
    channel?: ('campaign' | 'organic_search' | 'social' | 'referral' | 'direct') | null;
    /**
     * utm_medium (e.g. poster, qr, social, newsletter).
     */
    medium?: string | null;
    /**
     * utm_campaign.
     */
    campaign?: string | null;
    /**
     * utm_content — distinguishes creatives/variants.
     */
    content?: string | null;
    /**
     * Referring site host (e.g. instagram.com), when the browser sends one.
     */
    referrer?: string | null;
    /**
     * First path the visitor landed on this session.
     */
    landingPath?: string | null;
    /**
     * Random per-visit id (sessionStorage). Links this conversion to the behavioural funnel; not a stable identifier, not personal data.
     */
    sessionId?: string | null;
    /**
     * When attribution was first captured this session.
     */
    firstSeenAt?: string | null;
  };
  /**
   * Optional extra event data.
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Proof of cookie consent (GDPR Art. 7(1)). One row per interactive banner decision. No IP, no user agent — the random consent id matches the visitor's cfc_consent_id cookie. Never auto-purged.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records".
 */
export interface ConsentRecord {
  id: number;
  /**
   * Random id, also stored in the visitor's cfc_consent_id cookie so a stored consent can be matched to this record.
   */
  consentId: string;
  /**
   * Audience measurement: our own first-party analytics + Google Analytics.
   */
  statistics?: boolean | null;
  /**
   * Google Ads conversion tracking and ads personalisation.
   */
  marketing?: boolean | null;
  /**
   * Banner config version the choice was made against (CONSENT_CONFIG_VERSION). Identifies which wording the visitor saw.
   */
  configVersion?: number | null;
  /**
   * Language the banner was displayed in.
   */
  locale?: string | null;
  /**
   * Page the decision was made on.
   */
  path?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * CVs and other documents uploaded with a form submission. Private: only logged-in admins can open them. A file not attached to any submission within 24 hours is deleted automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applicant-files".
 */
export interface ApplicantFile {
  id: number;
  /**
   * Which form field the file was uploaded for (e.g. "cv").
   */
  kind?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            /**
             * Shown under the field, e.g. "PDF, max. 5 MB".
             */
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'upload';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            /**
             * Shown under the field.
             */
            description?: string | null;
            /**
             * One checkbox per option. The submission records the labels of the ticked options, so keep labels descriptive (e.g. "Tue 10 Nov · Lio").
             */
            options?:
              | {
                  label: string;
                  /**
                   * Stable key, e.g. "tue-lio". Not shown to visitors.
                   */
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkboxGroup';
          }
        | {
            name: string;
            label: string;
            /**
             * When the box is ticked, this form's questions appear below it (fields with a name that already exists in this form, e.g. "email", are asked only once). On submit a separate submission of that form is created, so its answers land with the other submissions of that form.
             */
            form: number | Form;
            /**
             * Optional text under the checkbox.
             */
            description?: string | null;
            /**
             * Optional link shown next to the checkbox, e.g. "What is the TechTour?". Opens in a new tab.
             */
            linkLabel?: string | null;
            /**
             * e.g. /techtour
             */
            linkUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'subform';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  /**
   * Your verdict on this applicant.
   */
  reviewStatus?: ('unreviewed' | 'accepted' | 'unsure' | 'rejected') | null;
  /**
   * Internal notes — never shown to the applicant. Included in the Excel export.
   */
  reviewNotes?: string | null;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Documents uploaded with this submission (e.g. the CV). Click one to open or download it.
   */
  files?: (number | ApplicantFile)[] | null;
  /**
   * Where this submission came from — captured from the landing URL (?src / utm_*) and carried through the session. Empty for direct/organic visits. Used only in aggregate for campaign analysis.
   */
  attribution?: {
    /**
     * Campaign tag from ?src=, or utm_source (e.g. "poster-tumsom").
     */
    source?: string | null;
    /**
     * Normalised traffic channel, derived from the tag + referrer: campaign (tagged link), organic_search, social, referral, or direct.
     */
    channel?: ('campaign' | 'organic_search' | 'social' | 'referral' | 'direct') | null;
    /**
     * utm_medium (e.g. poster, qr, social, newsletter).
     */
    medium?: string | null;
    /**
     * utm_campaign.
     */
    campaign?: string | null;
    /**
     * utm_content — distinguishes creatives/variants.
     */
    content?: string | null;
    /**
     * Referring site host (e.g. instagram.com), when the browser sends one.
     */
    referrer?: string | null;
    /**
     * First path the visitor landed on this session.
     */
    landingPath?: string | null;
    /**
     * Random per-visit id (sessionStorage). Links this conversion to the behavioural funnel; not a stable identifier, not personal data.
     */
    sessionId?: string | null;
    /**
     * When attribution was first captured this session.
     */
    firstSeenAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  team?: {
    /**
     * Allow clients to find team.
     */
    find?: boolean | null;
    /**
     * Allow clients to create team.
     */
    create?: boolean | null;
    /**
     * Allow clients to update team.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete team.
     */
    delete?: boolean | null;
  };
  projects?: {
    /**
     * Allow clients to find projects.
     */
    find?: boolean | null;
    /**
     * Allow clients to create projects.
     */
    create?: boolean | null;
    /**
     * Allow clients to update projects.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete projects.
     */
    delete?: boolean | null;
  };
  events?: {
    /**
     * Allow clients to find events.
     */
    find?: boolean | null;
    /**
     * Allow clients to create events.
     */
    create?: boolean | null;
    /**
     * Allow clients to update events.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete events.
     */
    delete?: boolean | null;
  };
  faq?: {
    /**
     * Allow clients to find faq.
     */
    find?: boolean | null;
    /**
     * Allow clients to create faq.
     */
    create?: boolean | null;
    /**
     * Allow clients to update faq.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete faq.
     */
    delete?: boolean | null;
  };
  sponsors?: {
    /**
     * Allow clients to find sponsors.
     */
    find?: boolean | null;
    /**
     * Allow clients to create sponsors.
     */
    create?: boolean | null;
    /**
     * Allow clients to update sponsors.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete sponsors.
     */
    delete?: boolean | null;
  };
  sponsorTiers?: {
    /**
     * Allow clients to find sponsor-tiers.
     */
    find?: boolean | null;
    /**
     * Allow clients to create sponsor-tiers.
     */
    create?: boolean | null;
    /**
     * Allow clients to update sponsor-tiers.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete sponsor-tiers.
     */
    delete?: boolean | null;
  };
  companies?: {
    /**
     * Allow clients to find companies.
     */
    find?: boolean | null;
    /**
     * Allow clients to create companies.
     */
    create?: boolean | null;
    /**
     * Allow clients to update companies.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete companies.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete media.
     */
    delete?: boolean | null;
  };
  blogPosts?: {
    /**
     * Allow clients to find blog-posts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create blog-posts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update blog-posts.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete blog-posts.
     */
    delete?: boolean | null;
  };
  forms?: {
    /**
     * Allow clients to find forms.
     */
    find?: boolean | null;
    /**
     * Allow clients to create forms.
     */
    create?: boolean | null;
    /**
     * Allow clients to update forms.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete forms.
     */
    delete?: boolean | null;
  };
  formSubmissions?: {
    /**
     * Allow clients to find form-submissions.
     */
    find?: boolean | null;
    /**
     * Allow clients to create form-submissions.
     */
    create?: boolean | null;
    /**
     * Allow clients to update form-submissions.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete form-submissions.
     */
    delete?: boolean | null;
  };
  siteConfig?: {
    /**
     * Allow clients to find site-config global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update site-config global.
     */
    update?: boolean | null;
  };
  membership?: {
    /**
     * Allow clients to find membership global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update membership global.
     */
    update?: boolean | null;
  };
  legal?: {
    /**
     * Allow clients to find legal global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update legal global.
     */
    update?: boolean | null;
  };
  partner?: {
    /**
     * Allow clients to find partner global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update partner global.
     */
    update?: boolean | null;
  };
  about?: {
    /**
     * Allow clients to find about global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update about global.
     */
    update?: boolean | null;
  };
  homepage?: {
    /**
     * Allow clients to find homepage global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update homepage global.
     */
    update?: boolean | null;
  };
  techTour?: {
    /**
     * Allow clients to find tech-tour global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update tech-tour global.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'team-groups';
        value: number | TeamGroup;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'sponsor-tiers';
        value: number | SponsorTier;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'waitlist-signups';
        value: number | WaitlistSignup;
      } | null)
    | ({
        relationTo: 'analytics-events';
        value: number | AnalyticsEvent;
      } | null)
    | ({
        relationTo: 'consent-records';
        value: number | ConsentRecord;
      } | null)
    | ({
        relationTo: 'applicant-files';
        value: number | ApplicantFile;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  role?: T;
  teamMemberships?:
    | T
    | {
        team?: T;
        role?: T;
        id?: T;
      };
  category?: T;
  image?: T;
  bio?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  companies?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-groups_select".
 */
export interface TeamGroupsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  ngoPartner?: T;
  slug?: T;
  featured?: T;
  description?: T;
  image?: T;
  technologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  status?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  team?:
    | T
    | {
        member?: T;
        role?: T;
        id?: T;
      };
  impactHeadline?: T;
  impact?: T;
  layout?:
    | T
    | {
        text?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              author?: T;
              role?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              layout?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        demo?:
          | T
          | {
              heading?: T;
              video?: T;
              poster?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              heading?: T;
              points?:
                | T
                | {
                    marker?: T;
                    timing?: T;
                    title?: T;
                    subtitle?: T;
                    state?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              heading?: T;
              members?:
                | T
                | {
                    member?: T;
                    role?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  time?: T;
  location?: T;
  description?: T;
  type?: T;
  isUpcoming?: T;
  link?:
    | T
    | {
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  tierRef?: T;
  tier?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsor-tiers_select".
 */
export interface SponsorTiersSelect<T extends boolean = true> {
  label?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  excerpt?: T;
  featuredImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  project?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-signups_select".
 */
export interface WaitlistSignupsSelect<T extends boolean = true> {
  email?: T;
  locale?: T;
  attribution?:
    | T
    | {
        source?: T;
        channel?: T;
        medium?: T;
        campaign?: T;
        content?: T;
        referrer?: T;
        landingPath?: T;
        sessionId?: T;
        firstSeenAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events_select".
 */
export interface AnalyticsEventsSelect<T extends boolean = true> {
  type?: T;
  path?: T;
  label?: T;
  locale?: T;
  attribution?:
    | T
    | {
        source?: T;
        channel?: T;
        medium?: T;
        campaign?: T;
        content?: T;
        referrer?: T;
        landingPath?: T;
        sessionId?: T;
        firstSeenAt?: T;
      };
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records_select".
 */
export interface ConsentRecordsSelect<T extends boolean = true> {
  consentId?: T;
  statistics?: T;
  marketing?: T;
  configVersion?: T;
  locale?: T;
  path?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applicant-files_select".
 */
export interface ApplicantFilesSelect<T extends boolean = true> {
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        upload?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        checkboxGroup?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              description?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        subform?:
          | T
          | {
              name?: T;
              label?: T;
              form?: T;
              description?: T;
              linkLabel?: T;
              linkUrl?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  reviewStatus?: T;
  reviewNotes?: T;
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  files?: T;
  attribution?:
    | T
    | {
        source?: T;
        channel?: T;
        medium?: T;
        campaign?: T;
        content?: T;
        referrer?: T;
        landingPath?: T;
        sessionId?: T;
        firstSeenAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  team?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  projects?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  events?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  faq?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  sponsors?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  sponsorTiers?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  companies?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  blogPosts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  forms?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  formSubmissions?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  siteConfig?:
    | T
    | {
        find?: T;
        update?: T;
      };
  membership?:
    | T
    | {
        find?: T;
        update?: T;
      };
  legal?:
    | T
    | {
        find?: T;
        update?: T;
      };
  partner?:
    | T
    | {
        find?: T;
        update?: T;
      };
  about?:
    | T
    | {
        find?: T;
        update?: T;
      };
  homepage?:
    | T
    | {
        find?: T;
        update?: T;
      };
  techTour?:
    | T
    | {
        find?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: number;
  clubName: string;
  tagline: string;
  description: string;
  email: string;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  windowTitle?: string | null;
  bookingUrl?: string | null;
  /**
   * Optional wide group photo shown at the top of the Team page. Left empty, the page starts straight at the member grid.
   */
  teamHeroImage?: (number | null) | Media;
  /**
   * Shown above the team photos, e.g. "20" or "20+". How many people are in the club — not how many have a profile on the site. Leave empty to hide it.
   */
  memberCount?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Controls the site colour theme. "Auto" shows each visitor light or dark based on their device/browser preference; the forced options apply one theme for everyone.
   */
  colorMode: 'auto' | 'dark' | 'light';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership".
 */
export interface Membership {
  id: number;
  title: string;
  description: string;
  /**
   * Optional hero image for the Join page — an aspirational candid (a hackathon, a build night). Left empty, the page stays text-only.
   */
  heroImage?: (number | null) | Media;
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The disciplines people can join in (e.g. Engineering, Consulting, Marketing, People & Ops). Shown as cards on the Join page to encourage cross-disciplinary applications.
   */
  tracks?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  contactEmail: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface Legal {
  id: number;
  impressum: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  privacyPolicy: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner".
 */
export interface Partner {
  id: number;
  /**
   * Page headline.
   */
  title?: string | null;
  /**
   * Lead paragraph under the headline.
   */
  intro?: string | null;
  /**
   * Optional hero image under the headline — e.g. the team collaborating with an NGO partner. Left empty, the page stays text-only.
   */
  heroImage?: (number | null) | Media;
  /**
   * The concrete things a partner gets from working with us.
   */
  valueProps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The steps of a partnership, from first conversation to hand-off.
   */
  process?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional: what we ask of a partner (time, a point of contact, etc.).
   */
  commitment?: string | null;
  ctaHeading?: string | null;
  ctaText?: string | null;
  contactEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  kicker?: string | null;
  /**
   * Page headline.
   */
  title?: string | null;
  lead?: string | null;
  /**
   * Narrative paragraphs.
   */
  story?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  valuesTitle?: string | null;
  values?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  teamTeaser?: string | null;
  teamCta?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroKicker?: string | null;
  heroCtaPrimary?: string | null;
  heroCtaSecondary?: string | null;
  heroScrollHint?: string | null;
  /**
   * Optional hero image beside the headline — ideally a wide candid of the team mid-build. Left empty, the hero stays text-only.
   */
  heroImage?: (number | null) | Media;
  aboutKicker?: string | null;
  aboutOneLiner?: string | null;
  aboutPitch?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Overrides the built-in process timeline (homepage and partner page). Add, remove or reorder steps freely — e.g. drop the MVP step or add an expansion step.
   */
  steps?:
    | {
        /**
         * Small badge above the title (e.g. "Week 0", "≈ 2 weeks in").
         */
        timing?: string | null;
        title: string;
        text: string;
        /**
         * Optional button on this step (e.g. "Book a first talk").
         */
        ctaLabel?: string | null;
        /**
         * Where the button links to. Left blank, it scrolls to the booking section of the page.
         */
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  processKicker?: string | null;
  processHeading?: string | null;
  processIntro?: string | null;
  projectsSubtitle?: string | null;
  projectsTitle?: string | null;
  projectsIntro?: string | null;
  eventsSubtitle?: string | null;
  eventsTitle?: string | null;
  eventsIntro?: string | null;
  sponsorsSubtitle?: string | null;
  sponsorsTitle?: string | null;
  sponsorsIntro?: string | null;
  qaSubtitle?: string | null;
  qaTitle?: string | null;
  qaIntro?: string | null;
  threedKicker?: string | null;
  threedTitle?: string | null;
  threedText?: string | null;
  threedCta?: string | null;
  ctaHeading?: string | null;
  ctaText?: string | null;
  ctaJoin?: string | null;
  ctaContact?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content of the Munich TechTour event page. The registration form is the form titled "techtour" under Forms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-tour".
 */
export interface TechTour {
  id: number;
  /**
   * Small line above the headline, e.g. "Munich TechTour · 9–13 November 2026".
   */
  kicker?: string | null;
  /**
   * Page headline.
   */
  title?: string | null;
  /**
   * Lead paragraph under the headline: what the TechTour is and who it is for.
   */
  intro?: string | null;
  /**
   * Optional hero image under the headline, e.g. a group photo at a company.
   */
  heroImage?: (number | null) | Media;
  /**
   * Untick to close registration: the page shows the "registration closed" message instead of the form.
   */
  registrationOpen?: boolean | null;
  /**
   * Optional. Shown on the page; once it has passed the form closes on its own.
   */
  registrationDeadline?: string | null;
  /**
   * One entry per visit, in date order. Use "To be announced" for a slot whose company is not fixed yet, and leave time/location empty while unknown — the page says so instead of showing a blank.
   */
  events?:
    | {
        /**
         * Company name, or "To be announced".
         */
        company: string;
        date: string;
        /**
         * Optional headline for the visit, e.g. "Startup evening at Lio". Defaults to the company name.
         */
        title?: string | null;
        /**
         * e.g. "18:00–20:00". Empty = "time to be announced".
         */
        time?: string | null;
        /**
         * Empty = "location to be announced".
         */
        location?: string | null;
        /**
         * What happens at this visit and why a student should come.
         */
        description?: string | null;
        /**
         * Company logo (SVG or PNG on transparent).
         */
        logo?: (number | null) | Media;
        website?: string | null;
        /**
         * "Tentative" marks a visit that is not certain yet; "To be announced" is a placeholder slot without a company.
         */
        status?: ('confirmed' | 'tentative' | 'tba') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Short cards, e.g. "Meet the engineers", "Office tours", "Free food & drinks".
   */
  highlights?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Explains the "I commit to attend" checkbox on the form: spots are limited and companies plan for headcount, so a registration is binding.
   */
  commitment?: string | null;
  /**
   * Heading above the registration form. Default: "Register for the TechTour".
   */
  formHeading?: string | null;
  /**
   * Shown instead of the form while registration is closed.
   */
  closedMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  clubName?: T;
  tagline?: T;
  description?: T;
  email?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  windowTitle?: T;
  bookingUrl?: T;
  teamHeroImage?: T;
  memberCount?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  colorMode?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership_select".
 */
export interface MembershipSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  heroImage?: T;
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        text?: T;
        id?: T;
      };
  tracks?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  impressum?: T;
  privacyPolicy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner_select".
 */
export interface PartnerSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  heroImage?: T;
  valueProps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  process?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  commitment?: T;
  ctaHeading?: T;
  ctaText?: T;
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  lead?: T;
  story?:
    | T
    | {
        text?: T;
        id?: T;
      };
  valuesTitle?: T;
  values?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  teamTeaser?: T;
  teamCta?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroKicker?: T;
  heroCtaPrimary?: T;
  heroCtaSecondary?: T;
  heroScrollHint?: T;
  heroImage?: T;
  aboutKicker?: T;
  aboutOneLiner?: T;
  aboutPitch?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        timing?: T;
        title?: T;
        text?: T;
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  processKicker?: T;
  processHeading?: T;
  processIntro?: T;
  projectsSubtitle?: T;
  projectsTitle?: T;
  projectsIntro?: T;
  eventsSubtitle?: T;
  eventsTitle?: T;
  eventsIntro?: T;
  sponsorsSubtitle?: T;
  sponsorsTitle?: T;
  sponsorsIntro?: T;
  qaSubtitle?: T;
  qaTitle?: T;
  qaIntro?: T;
  threedKicker?: T;
  threedTitle?: T;
  threedText?: T;
  threedCta?: T;
  ctaHeading?: T;
  ctaText?: T;
  ctaJoin?: T;
  ctaContact?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-tour_select".
 */
export interface TechTourSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  intro?: T;
  heroImage?: T;
  registrationOpen?: T;
  registrationDeadline?: T;
  events?:
    | T
    | {
        company?: T;
        date?: T;
        title?: T;
        time?: T;
        location?: T;
        description?: T;
        logo?: T;
        website?: T;
        status?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  commitment?: T;
  formHeading?: T;
  closedMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}